quarkus.hibernate-orm.persistence-xml.ignore=true
quarkus.hibernate-orm."icat".packages=org.icatproject.core.entity
quarkus.hibernate-orm."icat".datasource=icatdb
quarkus.hibernate-orm."icat".physical-naming-strategy=org.icatproject.quarkus.UpperCaseNamingStrategy
quarkus.datasource."icatdb".devservices.enabled=true

quarkus.cxf.path=/ICATService
quarkus.cxf.endpoint."/ICAT".implementor = org.icatproject.exposed.ICAT_CDI

quarkus.rest.path=/icat

quarkus.log.category."org.hibernate".level=ERROR
quarkus.log.category."org.icatproject".level=INFO

quarkus.docker.dockerfile-native-path=src/main/docker/Dockerfile.native-micro

quarkus.http.limits.max-form-attribute-size=1M
quarkus.http.limits.max-form-buffered-bytes=1M
