lifetimeMinutes = 120
rootUserNames = db/root
maxEntities = 10000
maxIdsInQuery = 500
importCacheSize = 50
exportCacheSize = 50
authn.list = db
authn.db.url = http://localhost:8080
authn.simple.url = http://localhost:8080
notification.list = Dataset Datafile
notification.Dataset = CU
notification.Datafile = CU
log.list = SESSION WRITE READ INFO
search.engine = LUCENE
search.urls = http://localhost:8080
search.populateBlockSize = 10000
search.searchBlockSize = 1000
search.directory = /home/ajkyffin/data/search
search.backlogHandlerIntervalSeconds = 60
search.enqueuedRequestIntervalSeconds = 3
search.aggregateFilesIntervalSeconds = 3600
search.maxSearchTimeSeconds = 5
key = wombat
